[[redirects]]
  from = "/"
  to = "/app-desktop.html"
  status = 200

[[redirects]]
  from = "/mobiel"
  to = "/app-mobile.html"
  status = 200

[[redirects]]
  from = "/reset-wachtwoord"
  to = "/reset-wachtwoord.html"
  status = 200
